RSDK-2062 Document build and run steps
viam-labs/wifi-sensor pull request #2
Opened 2023-03-09 20:53 UTC by maximpertsov

JIRA: https://viam.atlassian.net/browse/RSDK-2062

2023-03-11 01:05 UTC, Otterverse requested changes
Couple of small nits, but I also think you really need to list how to configure the component itself, not just the module.

2023-03-11 01:05 UTC, Otterverse commented on README.md
> +Alternatively, if you want to build this a binary for a different target environment, please use the [viam canon tool](https://github.com/viamrobotics/canon).
```suggestion
Alternatively, if you want to build a binary for a different target environment, please use the [viam canon tool](https://github.com/viamrobotics/canon).
```

2023-03-11 01:05 UTC, Otterverse commented on README.md
> +Copy the binary to in the environment where your Viam robot is running and add the following to your configuration:
```suggestion
Copy the binary to the robot (system where viam-server is running) and add the following to your configuration:
```

2023-03-11 01:05 UTC, Otterverse commented on README.md
> +  ...
I would also add the config for the wifi unit itself here. The part that would go in the "components" section.

2023-03-20 16:52 UTC, Otterverse approved these changes
LGTM

2023-03-20 16:52 UTC, Otterverse commented on README.md
> +      "attributes": {}
[nit] I think these could just be left out entirely, but no harm with them here either.

2023-03-21 19:09 UTC, maximpertsov commented on README.md
> +      "attributes": {}
```suggestion
      "model": "viam-labs:sensor:linux-wifi"
```

2023-03-21 19:10 UTC, merged